version: '3.9'

services:
  db-01:
    image: postgres:latest
    container_name: postgres_db_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_1:/var/lib/postgresql/data


volumes:
  postgres_data_1:
